export const mock = {
  accessToken: "l6FG_TYZjRCovrJirl-3D",
  allCards: [
    {"title":"Lorem ipsum dolor sit amet","description":"Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium","id":"6jam1Ly1iAN9U8Bd4P8GJ","creationDate":"Sun Sep 03 2023 20:12:34 GMT+0100 (British Summer Time)","authorId":"LubybFOjL3UKd2c5fQqRq"},
    {"title":"Excepteur sint occaecat cupidatat non proident","description":"Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur","id":"pdoeEMjMqyJSIWt2RvZlP","creationDate":"Sun Sep 03 2023 20:13:42 GMT+0100 (British Summer Time)","authorId":"LubybFOjL3UKd2c5fQqRq"},
    {"title":"At vero eos et accusamus","description":"Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus","id":"bsdKa-FQoWCz-mVAavCao","creationDate":"Sun Sep 03 2023 20:15:00 GMT+0100 (British Summer Time)","authorId":"l6FG_TYZjRCovrJirl-3D"},
    {"title":"Totam rem aperiam eaque ipsa","description":"Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis","id":"UrHW2Zii6lbFgoHjTz-cF","creationDate":"Sun Sep 03 2023 20:15:42 GMT+0100 (British Summer Time)","authorId":"l6FG_TYZjRCovrJirl-3D"},
    {"title":" Et harum quidem rerum facilis est et expedita distinctio","description":"Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum","id":"2cN9q784WXbY7d0A9EskP","creationDate":"Sun Sep 03 2023 20:16:29 GMT+0100 (British Summer Time)","authorId":"l6FG_TYZjRCovrJirl-3D"},
    {"title":"Ut enim ad minim veniam","description":"Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium","id":"jCpRcKFCjMTRENG8oDQ-m","creationDate":"Sun Sep 03 2023 20:17:09 GMT+0100 (British Summer Time)","authorId":"l6FG_TYZjRCovrJirl-3D"},
    {"title":"Ut enim ad minim veniam, quis nostrud exercitation ullamco","description":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","id":"DSOuLMBIE2rXe4q9tIzFm","creationDate":"Sun Sep 03 2023 20:18:49 GMT+0100 (British Summer Time)","authorId":"O34pczmR_JB5jrzgcIAHW"},
    {"title":"Itaque earum rerum hic tenetur a sapiente delectus","description":" At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti","id":"_Iy-oAzGdTZTIgbcS5p3S","creationDate":"Sun Sep 03 2023 20:19:37 GMT+0100 (British Summer Time)","authorId":"O34pczmR_JB5jrzgcIAHW"},
    {"title":"Lorem ipsum","description":"Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.","id":"XMA7uCy4HkgbtWszrNW8p","creationDate":"Sun Sep 03 2023 20:21:22 GMT+0100 (British Summer Time)","authorId":"AKawC7mB_-uEOUHLqTLmR"},
    {"title":"[(O_-_O)]","description":"<@'_'","id":"37B_oETKiDr22Kg9uaSvg","creationDate":"Sun Sep 03 2023 20:25:40 GMT+0100 (British Summer Time)","authorId":"-M3GOFQYEBFaA9_TeU8g8"},
    {"title":"Et harum quidem rerum facilis est et expedita distinctio","description":"At vero eos et accusamus et iusto odio dignissimos ducimus","id":"EsSpworBid0LAyMqaCM2p","creationDate":"Sun Sep 03 2023 20:26:42 GMT+0100 (British Summer Time)","authorId":"-M3GOFQYEBFaA9_TeU8g8"}
  ],
  allUsers: [
    {"name":"John Doe","email":"john@doe","password":"1234","id":"LubybFOjL3UKd2c5fQqRq","cardIds":["6jam1Ly1iAN9U8Bd4P8GJ","pdoeEMjMqyJSIWt2RvZlP"],"favoriteIds":[]},
    {"name":"Talia Hodge","email":"talia@hodge","password":"1234","id":"l6FG_TYZjRCovrJirl-3D","cardIds":["bsdKa-FQoWCz-mVAavCao","UrHW2Zii6lbFgoHjTz-cF","2cN9q784WXbY7d0A9EskP","jCpRcKFCjMTRENG8oDQ-m"],"favoriteIds":["37B_oETKiDr22Kg9uaSvg","2cN9q784WXbY7d0A9EskP","UrHW2Zii6lbFgoHjTz-cF","pdoeEMjMqyJSIWt2RvZlP","_Iy-oAzGdTZTIgbcS5p3S"]},
    {"name":"Rosie O'Neill","email":"rosi@oneill","password":"1234","id":"O34pczmR_JB5jrzgcIAHW","cardIds":["DSOuLMBIE2rXe4q9tIzFm","_Iy-oAzGdTZTIgbcS5p3S"],"favoriteIds":[]},
    {"name":"Magnus Carlsen","email":"magnus@carlsen","password":"1234","id":"AKawC7mB_-uEOUHLqTLmR","cardIds":["XMA7uCy4HkgbtWszrNW8p"],"favoriteIds":[]},
    {"name":"Sam Fisher","email":"sam@fisher","password":"1234","id":"8u0NaJcr_iYBPNSBOemLO","cardIds":[],"favoriteIds":[]},
    {"name":"Mr. Nobody","email":"mr@nobody","password":"1234","id":"-M3GOFQYEBFaA9_TeU8g8","cardIds":["37B_oETKiDr22Kg9uaSvg","EsSpworBid0LAyMqaCM2p"],"favoriteIds":[]}
  ],
}
